### ISSUE TITLE
Ordering of doctype w.r.t. siblings not preserved

### ISSUE THREAD

**Issue by bwrrp** [nrkn/dom-treeadapter#4]
Parsing the following html results in a DOM where the order of the comment and doctype is swapped - `document.firstChild` is the doctype, but it should be the comment:
```
<!-- comment -->
<!doctype html>
<p>Hello!</p>
```

This appears to be due to [this](https://github.com/nrkn/dom-treeadapter/blob/master/index.js#L55) `if` in `setDocumentType`. A doctype must appear before the root element, but not necessarily before the first childnode of the Document. Therefore, it may be better to change this check to `if (document.documentElement)`.

**Comment by nrkn** [comment]
Turns out just removing that whole middle case does the trick - this is more similar to the default adapter behaviour too.

Input:

```html
<!-- comment --><!DOCTYPE html><p>Hello!</p>
```

Output:

```html
<!-- comment --><!DOCTYPE html><html><head></head><body><p>Hello!</p></body></html>
```

Wish I could remember why that middle case was there!
